### ISSUE TITLE
In userguide, specify how to set CMAKE_BUILD_TYPE to RELEASE

### ISSUE THREAD

**Issue by surchs** [BIC-MNI/minc-toolkit#24]
Hi,

I am not sure if this repo is intended for developers only but I thought you might find the feedback useful that for the average user this hint: 
**Important: set CMAKE_BUILD_TYPE to RELEASE, or face severe speed degradation of some tools** 
will probably not be straightforward. 

I spent a good while searching for how to set the cmake_build_type but apart from an inconclusive stackoverflow thread didn't find much information. So if you could clarify this step, that would be grand.

Thanks!

**Comment by vfonov** [comment]
it's it pretty trivial if you run ccmake - it is one of the options visible on the screen.
Alternatively one can set it with cmake -DCMAKE_BUILD_TYPE:STRING=Release .

**Comment by vfonov** [comment]
Also, this is is the first link that shows up if you google cmake CMAKE_BUILD_TYPE  :
http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html

**Comment by surchs** [comment]
Hey, thanks for the quick reply. I didn't find your link but I checked the man-page. I did not find the code snippet you posted. Maybe it's just difficult for me but I could imagine that there may be others. Just to be clear, I don't see this as a real issue, more of a feedback.
