### ISSUE TITLE
CMake 3.0 or higher is required.

### ISSUE THREAD

**Issue by fristed** [BIC-MNI/minc-toolkit#25]
I just pulled the latest changes on master and got:

CMake Error at CMakeLists.txt:5 (cmake_minimum_required):
   CMake 3.0 or higher is required.  You are running version 2.8.12.2

I guess this is really not an issue, except that it is very inconvenient to upgrade CMake when running Ubuntu LTS. Why suddenly this requirement?

My Ubuntu 14.04.2 LTS is fully updated and has only version 2.8.12.2. I'm bringing this up because it will affect many users.

**Comment by gdevenyi** [comment]
Cmake upgrade here https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x

**Comment by vfonov** [comment]
Technically , if you remove that line , it will build with cmake 2.8.12.2  , but I was trying to reduce the warnings that newer cmake was producing so included cmake policy settings which are not compatible with 2.8.12

**Comment by vfonov** [comment]
I reverted the requirement for 3.0 to 2.8

**Comment by fristed** [comment]
Ok. Now ITK makes trouble:
Policy "CMP0054" is not known to this version of CMake.
To fix it, I inserted a check for that particular policy.

**Comment by vfonov** [comment]
did you insert it into ITK ?

**Comment by fristed** [comment]
Yes
