### ISSUE TITLE
Makefile:146: recipe for target 'all' failed

### ISSUE THREAD

**Issue by surchs** [BIC-MNI/minc-toolkit#28]
Hi,

I just tried to build the toolkit following the instructions on the git page. It failed with the following error messages:

```
Makefile:553: recipe for target 'h5tools_dump.lo' failed
make[5]: *** [h5tools_dump.lo] Error 1
Makefile:497: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
Makefile:539: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
CMakeFiles/HDF5.dir/build.make:111: recipe for target 'HDF5-prefix/src/HDF5-stamp/HDF5-build' failed
make[2]: *** [HDF5-prefix/src/HDF5-stamp/HDF5-build] Error 2
CMakeFiles/Makefile2:130: recipe for target 'CMakeFiles/HDF5.dir/all' failed
make[1]: *** [CMakeFiles/HDF5.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

Any suggestions?

**Comment by vfonov** [comment]
What OS, version, compiler, cmake parameters ?

**Comment by surchs** [comment]
1. Debian
2. Testing
3. How do I find out?
4. Default

**Comment by vfonov** [comment]
create a separate building directory, set build type ( CMAKE_BUILD_TYPE )  to Release

**Comment by surchs** [comment]
Unless I misunderstand, that's already what I am doing 
```
 git clone --recursive git://github.com/BIC-MNI/minc-toolkit.git minc-toolkit
  cd minc-toolkit
  mkdir build && cd build
  ccmake .. # Enter the location of all dependencies, if not detected automatically ..., 
  make && make test && make install
```

This is the instruction I am following. I now also set the CMAK_BUILD_TYPE flag explicitly to Release. I still get an error:

```
Makefile:553: recipe for target 'h5tools_dump.lo' failed
make[5]: *** [h5tools_dump.lo] Error 1
Makefile:497: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
Makefile:539: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
CMakeFiles/HDF5.dir/build.make:111: recipe for target 'HDF5-prefix/src/HDF5-stamp/HDF5-build' failed
make[2]: *** [HDF5-prefix/src/HDF5-stamp/HDF5-build] Error 2
CMakeFiles/Makefile2:130: recipe for target 'CMakeFiles/HDF5.dir/all' failed
make[1]: *** [CMakeFiles/HDF5.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

Should I save the entire log?

**Comment by vfonov** [comment]
That would help, together with output of cmake -LA .

**Comment by surchs** [comment]
Here is the [cmake log](https://gist.github.com/surchs/e044090362b8c155ddb8) and the [log of the make command](https://gist.github.com/surchs/0f9e570fa921e39d16bc).

**Comment by TheChymera** [comment]
I am getting the same error - [here](https://bpaste.net/show/0a2da3466e11) is a longer tail of my log.

**Comment by TheChymera** [comment]
It seems the error is starting here:

```
[01m[Kh5tools_dump.c:635:9:[m[K [01;31m[Kerror: [m[Kexpected expression before '[01m[K/[m[K' token
         //HGOTO_ERROR(dimension_break, H5E_tools_min_id_g, "Could not allocate buffer for ptdata");
```

Looks like maybe some typo in your code?

**Comment by rdvincent** [comment]
Looks like your compiler might be choking on a "//" comment in that C source file. Which compiler are you using?

The offending file is part of HDF5, which we use but don't provide ourselves. As a workaround, you could separately install a version of HDF5 for your OS, and enable the USE_SYSTEM_HDF5 option in the CMake build.

**Comment by gdevenyi** [comment]
Looks to me like problems with character encoding, @TheChymera are you running a non-english base system?

**Comment by TheChymera** [comment]
@rdvincent  see above post for my compiler

@gdevenyi English, UTF-8

**Comment by vfonov** [comment]
Looks like this error was fixed in HDF5 version 1.8.13 - I will update to the latest HDF5 - hopefully that would  be enough

**Comment by vfonov** [comment]
@TheChymera  @surchs  - can you try to build the latest develop branch ?

**Comment by TheChymera** [comment]
@vfonov 

sci-libs/hdf5-1.8.15_p1 builds nicely here on my end. Currently trying to see if I can set CMake to unbundle that,

**Comment by rdvincent** [comment]
the current develop branch now fails for me on both Ubuntu 12.04 and CentOS 6.6, with the same error:

dsets.cpp: In function ‘herr_t test_create(H5::H5File&)’:
dsets.cpp:128:34: error: ‘class H5::DataSet’ has no member named ‘getObjName’

**Comment by vfonov** [comment]
Did you start with a fresh build directory?

**Comment by rdvincent** [comment]
No. Trying again.

**Comment by rdvincent** [comment]
Ok. that was it. sorry.

**Comment by eykn** [comment]
how to solve this error

Makefile:1219: recipe for target '../out/gcc-debug//src/inet/linklayer/ieee80211                                                                                                                mesh/locator/LocatorModule.o' failed
make[1]: *** [../out/gcc-debug//src/inet/linklayer/ieee80211mesh/locator/Locator                                                                                                                Module.o] Error 1
make[1]: Leaving directory '/c/omnetpp-4.6/inetmanet-2.0-inetmanet-3.0/src'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cjm399** [comment]
Here is how I fixed this for myself. Not sure if this will work for everyone. My int main() was returning a 1 at the end. I changed this to be "return 0;" Then the error went away. Not sure why, maybe someone with more experience could explain this.

**Comment by vfonov** [comment]
Hmm... I think our problem was with older version of HDF5 that was resolved using newer one.

**Comment by djlimdiwala** [comment]
while executing Makefile, I am getting this error..

make[2]: [init] Error 126 (ignored)
make ../obj/i686-m64/STAMP ../bin/i686-m64/STAMP
make[3]: Entering directory '/home/djlimdiwala/srilm/misc/src'
make[3]: '../obj/i686-m64/STAMP' is up to date.
mkdir ../bin/i686-m64/
mkdir: cannot create directory ‘../bin/i686-m64/’: No such file or directory
/home/djlimdiwala/srilm//common/Makefile.common.targets:80: recipe for target '../bin/i686-m64/STAMP' failed
make[3]: [../bin/i686-m64/STAMP] Error 1 (ignored)
touch ../bin/i686-m64/STAMP
touch: cannot touch '../bin/i686-m64/STAMP': No such file or directory
/home/djlimdiwala/srilm//common/Makefile.common.targets:80: recipe for target '../bin/i686-m64/STAMP' failed
make[3]: *** [../bin/i686-m64/STAMP] Error 1
make[3]: Leaving directory '/home/djlimdiwala/srilm/misc/src'
/home/djlimdiwala/srilm//common/Makefile.common.targets:21: recipe for target 'init' failed
make[2]: *** [init] Error 2
make[2]: Leaving directory '/home/djlimdiwala/srilm/misc/src'
Makefile:109: recipe for target 'init' failed
make[1]: *** [init] Error 1
make[1]: Leaving directory '/home/djlimdiwala/srilm'
Makefile:57: recipe for target 'World' failed
make: *** [World] Error 2



Can you help resolving this??

**Comment by Aspect9** [comment]
struggling to install xwin on me Parrot Os... a real hum-dinger*

**Comment by ajith4ab** [comment]
root@Ajith:~/Desktop/install_folder# bash install.sh
##################################################
Realtek Wi-Fi driver Auto installation script
Novembor, 21 2011 v1.1.0
##################################################
Decompress the driver source tar ball:
	
rtl8192EU_linux_v4.2.2_7585.20130524
Authentication requested [root] for make clean:
cd hal/OUTSRC/ ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal/OUTSRC/ ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko 
cd hal/led ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd hal ; rm -fr */*/*.mod.c */*/*.mod */*/*.o */*/.*.cmd */*/*.ko
cd hal ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core/efuse ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep/linux ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
rm -fr Module.symvers ; rm -fr Module.markers ; rm -fr modules.order
rm -fr *.mod.c *.mod *.o .*.cmd *.ko *~
rm -fr .tmp_versions
Authentication requested [root] for make driver:
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.14.0-kali1-amd64/build M=/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524  modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
  CC [M]  /root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/core/rtw_cmd.o
In file included from /root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/include/drv_types.h:32:0,
                 from /root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/core/rtw_cmd.c:22:
/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/include/osdep_service.h: In function ‘thread_enter’:
/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/include/osdep_service.h:251:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/include/osdep_service.h: In function ‘flush_signals_thread’:
/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/include/osdep_service.h:261:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
      timer_pending
/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/include/osdep_service.h:263:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.14.0-kali1-common/scripts/Makefile.build:319: recipe for target '/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/core/rtw_cmd.o' failed
make[4]: *** [/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.14.0-kali1-common/Makefile:1520: recipe for target '_module_/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524' failed
make[3]: *** [_module_/root/Desktop/install_folder/driver/rtl8192EU_linux_v4.2.2_7585.20130524] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
Makefile:1043: recipe for target 'modules' failed
make: *** [modules] Error 2
##################################################
Compile make driver error: 2
Please check error Mesg
##################################################




how to fix ?????

**Comment by mymuzk** [comment]
The following worked for me when I ran into this error:

make clean
./configure CFLAGS=-fPIC CXXFLAGS=-fPIC
make

**Comment by athirasivaraj** [comment]
How to solve this error??
![screenshot from 2018-03-29 18-50-24](https://user-images.githubusercontent.com/34681359/38091081-1c0d4740-3382-11e8-8cef-f1ba7d219751.png)

**Comment by athirasivaraj** [comment]
I also face the same error. Please help me with this
![screenshot from 2018-03-30 10-32-40](https://user-images.githubusercontent.com/34681359/38349363-4c100788-38c4-11e8-92bf-fa0bad21abfc.png)

**Comment by sepideh9191** [comment]
@vfonov 
hi 
i have this error how can I solve it?
Makefile:51: recipe for target 'src/Makefile' failed
make: *** [src/Makefile] Error 1

**Comment by gdevenyi** [comment]
@sepideh9191 please open a seperate issue and provide *full* description of how you acquired the source, how you configured the build, and the full output log of the compile.

**Comment by gdevenyi** [comment]
Original reporter is long gone, closing

**Comment by sepideh9191** [comment]
@surchs gdevenyi
i appreciate the time that you devoted.
excuse me i did not understand so mush.

**Comment by colzez** [comment]
how to solve this plz
make: *** [Makefile:95: out/gcc-release//inet] Error 1

**Comment by gdevenyi** [comment]
@colzez Please don't hijack other threads. Open a new issues with full details of how you obtained the source, configured it, and built it, including OS and compiler versions and full logs.
