### ISSUE TITLE
minc-toolkit or MINC

### ISSUE THREAD

**Issue by TheChymera** [BIC-MNI/minc-toolkit#30]
Hi guys, is this software distribution an equivalent to [MINC (as seen here)](https://en.wikibooks.org/wiki/MINC/Tutorials/SourceInstall)?

I notice that the install dependencies are more reduced for minc-toolkit. Does minc-toolkit supersede MINC? Is it just MINC with some additional bundled stuff?

**Comment by rdvincent** [comment]
minc-toolkit is includes many individual MINC-related subprojects that used to be distributed and built separately. The entire source tree is now built using CMake, so the build instructions on the website you cite may not work for all subprojects.
