### ISSUE TITLE
does minc-tolkit provide the MNI deps for freesurfer?

### ISSUE THREAD

**Issue by TheChymera** [BIC-MNI/minc-toolkit#34]
Fresurfer [bundles quite a few of its deps](ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/src/).

MNI is one of them. Does the minc-toolkit provide the same files?

**Comment by vfonov** [comment]
minc-toolkit works with minc files, if that's the question. MNI - is Montreal Neurological Institute

**Comment by TheChymera** [comment]
Sorry for not being more specific. 

the README at this address: ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/src/mni.srcbuild.June2015.README.txt

describes a number of (bundled) dependencies of Freesurfer that are collectively named mni.srcbuild. I am unsure what the overlap between that and mni-toolkit is. Does the mni-toolktit provide all of:

 * MINC            v1.5.1
 * NetCDF          v3.6.0-p1
* MNI Perllib     v0.07
* N3              v1.12.0
* EBTKS           v1.6.4
* Getopt-Tabular  v0.3
* MNI autoreg     v0.99.6
* MNI models      v1.1

Also, in how far should I be mindful of the versions? do you know whether Freesurfer works with the currently provided dependency versions of minc-toolkit?

**Comment by rdvincent** [comment]
The current minc-toolkit is a superset of the MINC code shipped with FS.
The version included with FreeSurfer is over ten years old. I would _guess_
that FreeSurfer might function with the newer MINC tools, but the actual
results would differ materially. However, we do not test our code against
FreeSurfer, so it might not function at all.

**Comment by TheChymera** [comment]
@rdvincent  So all the packages I listed are also contained in minc-toolkit (and then some)? For instance I cannot find “Getopt-Tabular” and “MNI models” in the package list of minc-toolkit.

**Comment by rdvincent** [comment]
Minc-toolkit should contain a version of getopt-tabular. The models are in
a separate Github project, bic-mni-models.

In any case, I can't recommend using newer MINC tools with FreeSurfer.
Nobody has tested this, to the best of my knowledge.

    -bert

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/minc-toolkit/tree/master/perl-modules/Getopt-Tabular-0.3
