### ISSUE TITLE
I'm a newbie here as well as for kernel programming, kindly help me with this error

### ISSUE THREAD

**Issue by chintalapudikrishna** [BIC-MNI/minc-toolkit#41]
i'm using 
ubuntu 16.04 LTS
OS type 32-bit
Also recently updated kernel header package
make -C /lib/modules/4.4.0-34-generic/build M=/root/pluto modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-34-generic'
make[2]: *** No rule to make target '/root/pluto/pluto2.c', needed by '/root/pluto/pluto2.o'.  Stop.
Makefile:1403: recipe for target '_module_/root/pluto' failed
make[1]: *** [_module_/root/pluto] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-34-generic'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vfonov** [comment]
This is not relevant to minc-toolkit, maybe https://kernelnewbies.org/ will help.
