### ISSUE TITLE
Cannot open file on Display

### ISSUE THREAD

**Issue by SamPare** [BIC-MNI/minc-toolkit#59]
Hi, I am relatively new to programming and I installed the minc-toolkit 1.9.18 and for some reasons I cannot open any files with Display. Here is the code : 

Display mni_icbm152_csf_tal_nlin_sym_09c.mnc
Input mni_icbm152_csf_tal_nlin_sym_09c.mnc
/Users/vfonov/src/minc-toolkit-v2/libminc/libsrc/netcdf_convenience.c:573 (from miopen): Unable to open file 'mni_icbm152_csf_tal_nlin_sym_09c.mnc'
Error: opening MINC file "mni_icbm152_csf_tal_nlin_sym_09c.mnc".
Error loading mni_icbm152_csf_tal_nlin_sym_09c.mnc

This happens with every file I try (all are from the icbm and best library packages). 
Do you have any ideas why it does that and how I can fix it? 

Thank you,
Your new fellow Samuel

**Comment by gdevenyi** [comment]
Hi.

1. This is minc-toolkit, not minc-toolkit-v2 repo.

2. Please provide the complete details of how you installed, and what system you're running on.

**Comment by gdevenyi** [comment]
Please move this issue to the -v2 repo.

**Comment by SamPare** [comment]
Thank you for your quick response! I have moved this to the v2 repo.
